# Faktorisering

In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
heroes = pd.read_csv("../FASERIP.csv")
heroes.head()

,character,F,A,S,E,R,I,P,Type,Flight,Armour,Ranged,Alignment
0,Angel,20,30,10,30,10,6,10,Mutant,6,0,0,Hero
1,Aurora,20,20,6,20,4,10,4,Mutant,150,0,0,Hero
2,Beast,40,40,30,20,20,10,20,Mutant,0,0,0,Hero
3,Black Knight,30,20,10,10,10,6,6,Human,0,10,0,Hero
4,Box,30,30,75,75,20,10,10,Technological,40,50,0,Hero

In [3]:
# Select only the FASERIP columns
stats_only = heroes[['F', 'A', 'S', 'E', 'R', 'I', 'P']]

# Initialize the scaler
scaler = StandardScaler()

# "Fit and Transform" the data (this makes the mean 0 and variance 1)
stats_scaled = scaler.fit_transform(stats_only)

In [4]:
# We'll ask for all 7 components initially
pca = PCA(n_components=7)

# Run the math
pca.fit(stats_scaled)

PCA(n_components=7)

In [5]:
# This prints the percentage of variance for each component
print(pca.explained_variance_ratio_)

[0.33120743 0.1907864  0.15925742 0.13065295 0.08194655 0.07154762
 0.03460162]

In [6]:
# Create a DataFrame of the loadings
loadings = pd.DataFrame(
    pca.components_.T, 
    columns=[f'PC{i+1}' for i in range(7)],
    index=['F', 'A', 'S', 'E', 'R', 'I', 'P']
)

print(loadings)

        PC1       PC2       PC3       PC4       PC5       PC6       PC7
F  0.510762  0.012178  0.171820 -0.102375 -0.222362  0.803061 -0.067966
A  0.333631  0.122343  0.551127  0.425685  0.603812 -0.100463  0.118708
S  0.536851 -0.249466 -0.271180 -0.070651 -0.129686 -0.265704  0.695421
E  0.551723 -0.054354 -0.304069  0.136363 -0.033608 -0.334865 -0.684347
R -0.056802  0.496059 -0.355312  0.716174 -0.258321  0.137985  0.160552
I  0.145932  0.589593  0.445035 -0.280518 -0.472210 -0.362005  0.017515
P  0.103357  0.570965 -0.420043 -0.439464  0.527547  0.110362  0.057134

In [7]:
# Create the coordinates
hero_scores = pca.transform(stats_scaled)

# Turn it into a nice DataFrame with the Hero names
hero_mapped = pd.DataFrame(hero_scores, columns=[f'PC{i+1}' for i in range(7)])
hero_mapped.insert(0, 'character', heroes['character'])

hero_mapped.head()

,character,PC1,PC2,PC3,PC4,PC5,PC6,PC7
0,Angel,-0.737911,-0.817428,0.469833,0.317715,0.517607,0.282464,-0.269113
1,Aurora,-1.228300,-1.124965,0.736876,-0.286325,0.048132,0.336401,-0.251259
2,Beast,0.273347,-0.033818,0.493285,0.664780,0.474395,1.174318,0.739517
3,Black Knight,-1.141464,-0.956024,0.589738,-0.021678,-0.052804,1.071215,0.199971
4,Box,1.986421,-0.983128,-0.917882,0.897851,-0.343771,-0.551529,0.282893

In [16]:
from sklearn.decomposition import FactorAnalysis

In [17]:
fa = FactorAnalysis(n_components=3, random_state=42)

In [18]:
fa.fit(stats_scaled)

FactorAnalysis(n_components=3, random_state=42)

In [19]:
loadings = pd.DataFrame(
    fa.components_.T,
    index=stats_only.columns,
    columns=["Factor1", "Factor2", "Factor3"]
)

print(loadings)

    Factor1   Factor2   Factor3
F  0.594498  0.283590 -0.290222
A  0.296217  0.352842 -0.163186
S  0.856971 -0.177226 -0.074261
E  0.861955  0.033426  0.186770
R -0.063115  0.237808  0.509069
I  0.043139  0.581105 -0.099672
P  0.107675  0.253656  0.247982