In [9]:
import pandas as pd

df = pd.read_csv("smartphones.csv")

df.head()

  User_ID  Age  ... Caffeine_Intake_Cups Weekend_Screen_Time_Hours
0      U1   58  ...                    1                       8.7
1      U2   25  ...                    3                       5.1
2      U3   19  ...                    5                       6.3
3      U4   35  ...                    6                      12.8
4      U5   33  ...                    5                       9.9

[5 rows x 13 columns]

In [10]:
df.dtypes

User_ID                       object
Age                            int64
Gender                        object
Occupation                    object
Device_Type                   object
Daily_Phone_Hours            float64
Social_Media_Hours           float64
Work_Productivity_Score        int64
Sleep_Hours                  float64
Stress_Level                   int64
App_Usage_Count                int64
Caffeine_Intake_Cups           int64
Weekend_Screen_Time_Hours    float64
dtype: object

In [11]:
df.shape

(50000, 13)

In [13]:
df.describe().round(2)

            Age  ...  Weekend_Screen_Time_Hours
count  50000.00  ...                   50000.00
mean      39.03  ...                       8.01
std       12.41  ...                       3.46
min       18.00  ...                       2.00
25%       28.00  ...                       5.00
50%       39.00  ...                       8.00
75%       50.00  ...                      11.00
max       60.00  ...                      14.00

[8 rows x 9 columns]

In [14]:
df['Stress_Level'].value_counts().sort_index()

Stress_Level
1     4940
2     5058
3     5009
4     4871
5     5096
6     5076
7     4933
8     4993
9     4993
10    5031
Name: count, dtype: int64